[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.api"

[project]
name = "zinescape"
authors = [
    { name = "Thaddeus Hughes", email = "hughes.thad@gmail.com" },
]
dynamic = ["version"]
description = "tools for making zines with inkscape"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pypdf",
]

[project.scripts]
zinescape = "zinescape.zinescape:cli"
